### PR TITLE
Add applet/desklet highlighting to all themes

### PR DESCRIPTION
**Pull request by collinss**

### CODE REVIEW

**Comment by JosephMcc** [comment]
Could I ask a favor when doing this? When theming multiple items use the styling used in the rest of the theme. Put each item on its own line

item1,
item2,
item3
{

instead of item1, item2, item3 {}

**Comment by JosephMcc** [comment]
Are you sure you are doing this correctly? Shouldn't it be

.desklet:highlight,
.desklet-with-borders:highlight,
.desklet-with-borders-and-header:highlight

**Comment by collinss** [comment]
Oh, good catch. I just pulled from what I did in the fallback theme, but apparently I managed to mess that up as well. I'll fix it when I get the chance.

**Comment by collinss** [comment]
@JosephMcc, Fixed

**Pull request merged**
